services:
  # nginx with ModSecurity (Web Application Firewall)
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.modsecurity
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      # Mount logs for monitoring
      - ./logs/nginx:/var/log/nginx
      - ./logs/modsecurity:/var/log/modsecurity
    environment:
      - NGINX_HOST=localhost
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - buildkite-net

  # Buildkite Overview Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_REVISION: ${GIT_REVISION:-unknown}
    expose:
      - "8000"
    environment:
      - DENO_ENV=${DENO_ENV:-production}
      - DATA_DIR=/app/data
    volumes:
      # Mount database and logs
      - ./data:/app/data
      - ./logs/app:/app/logs
      # Mount .env file
      - ./.env:/app/.env:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - buildkite-net

networks:
  buildkite-net:
    driver: bridge

volumes:
  nginx-logs:
  modsecurity-logs:
  app-data:
  app-logs:
