apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildkite-overview-data
  labels:
    app: buildkite-overview
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "local-path"
